services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecom_db_source
    ports:
      - "5433:5432"
    volumes:
      - postgres_db_source_data:/var/lib/postgresql/data
    networks:
      - ecom-airflow_20dd52_airflow

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - ecom-airflow_20dd52_airflow

volumes:
  postgres_db_source_data:
  pgadmin_data:

networks:
  ecom-airflow_20dd52_airflow:
    external: true
