name: 'ecom_data_model'
version: '1.0.0'
profile: 'motherduck'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +database: ecom_db
  ecom_data_model:
    ecom_staging:
      +materialized: view

    # Intermediate models
    ecom_intermediate:
      +materialized: table
      +schema: ecom_intermediate
      +tags: ["intermediate"]
    
    # Mart models
    ecom_marts:
      +materialized: table
      +schema: ecom_marts
      +tags: ["marts"]

vars:
  # Add any variables you might need
  'dbt_date:time_zone': 'America/New_York'
  schema_prefix: ''

seeds:
  ecom_data_model:
    +schema: ecom_raw

tests:
  +store_failures: true
  +severity: error