name: 'ecom_staging'
version: '1.0.0'
config-version: 2

profile: 'motherduck'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecom_data_model:
    # Config indicated by + and applies to all files under models/example/
    ecom_staging:
      +materialized: view
      snowflake_warehouse: ECOM_WH
      schema: ecom_staging