name: 'ecom_staging'
version: '1.0.0'
config-version: 2

profile: 'motherduck'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecom_data_model:
    ecom_staging:
      +materialized: view
      +schema: ecom_staging
      +persist_docs:
        relation: true
        columns: true
    config:
      persist_database: true

vars:
  source_database: 'ecom_db'
  
seeds:
  ecom_staging:
    +schema: ecom_staging
    +persist_docs:
      relation: true